### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Cubik65536** [OpenCubikFoundation/theopensourceway-guidebook-zh#1]
## Rules

If you want to contribute, you can pick one of the following chapters and comment below telling me (by `@Cubik65536`) what chapter you want to work on. I will create another issue and assign it to you and related works will be tracked by that issue.

如果你想要向其中的某个页面贡献，请在该页面的 Issue 下方留言并 `@` 我 (`@Cubik65536`) 告知你想要贡献的页面。我会开启另外一个 issue 并将其分配给你，对该页面的内容的工作将在新 issue 内跟踪。

## TODO-List

- [ ] Add Source Text (Issue #)
- [ ] Presenting the Open Source Way (Issue #)
    - [ ] The Shape of Things (I.e., Assumptions We Are Making) (Issue #)
    - [ ] Structure of This Guide (Issue #)
    - [ ] A Community of Practice Always Rebuilding Itself (Issue #)
- [ ] Getting Started (Issue #)
    - [ ] Community 101: Understanding, Joining, or Forming a New Community (Issue #)
    - [ ] New Project Checklist (Issue #)
    - [ ] Creating an Open Source Product Strategy (Issue #)
- [ ] Attracting Users (Issue #)
    - [ ] Communication Norms in Open Source Software Projects (Issue #)
    - [ ] To Build Diverse Open Source Communities, Make Them Inclusive First (Issue #)
- [ ] Guiding Participants (Issue #)
    - [ ] Why Do People Participate in Open Source Communities? (Issue #)
- [ ] Growing Contributors (Issue #)
    - [ ] From Users to Contributors (Issue #)
    - [ ] What Is a Contribution? (Issue #)
    - [ ] Essentials of Building a Community (Issue #)
    - [ ] Onboarding (Issue #)
    - [ ] Creating a Culture of Mentorship (Issue #)
    - [ ] Project and Community Governance (Issue #)
    - [ ] Community Roles (Issue #)
    - [ ] Community Manager Self-Care (Issue #)
- [ ] Measuring Success (Issue #)
    - [ ] Defining Healthy Communities (Issue #)
    - [ ] Understanding Community Metrics (Issue #)
    - [ ] Announcing Software Releases (Issue #)
